### ISSUE TITLE
Can't get it working in IE8

### ISSUE THREAD

**Issue by corysimmons** [saabi/vminpoly#37]
![image](https://cloud.githubusercontent.com/assets/224636/12629424/e71555a0-c515-11e5-8667-a8cf7a4e1bcb.png)

That `<p>1</p>` element  has the following style:

```css
p {
  height: 30vh;
  background: black;
  width: 100%;
}
```

Here is the result (not fixing the `<p>` to `30vh`):

![image](https://cloud.githubusercontent.com/assets/224636/12629474/1a4424b0-c516-11e5-8dc7-8d43d5d5dd20.png)

Would appreciate any help!
